### ISSUE TITLE
Forma recursiva

### ISSUE THREAD

**Issue by pedrovelasquez9** [pedrovelasquez9/retos-de-programacion#5]
@OviDeveloperGit una cosa, probando tu solución he encontrado dos cosas:

- El input, aunque por consola pase un número, siempre es igual a 20
- En la solución recursiva, la secuencia comienza en 0, pero la salida, según el enunciado, debería ser 1, 1, 2, 3... valida que la secuencia comience en 1 al mostrarla

**Comment by CesarM4rtinez** [comment]
Que soluciones me sugieres?
